name: CI

on:
  push:
    branches:
      - dev*
    tags:
      - v*
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

env:
  OPENWRT_VERSION: "24.10.5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        run: |
          date +"%Y-%m-%d %H:%M:%S" > Packages
          date +"%Y-%m-%d %H:%M:%S" > Packages.gz
          date +"%Y-%m-%d %H:%M:%S" > Packages.sig
          date +"%Y-%m-%d %H:%M:%S" > test.ipk

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout ${{ env.OPENWRT_VERSION }}
          git pull
          git add Packages
          git add Packages.*
          git add *.ipk
          git commit -m "Add xray_core binary via workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          branch: ${{ env.OPENWRT_VERSION }}
